// =============================================================================
// Generated Supabase database types — The Witness
//
// Generated by scripts/generate-db-types.js (direct SQL introspection of
// information_schema/pg_catalog over a plain Postgres connection), NOT
// by the official `supabase gen types typescript` CLI. See that script's
// own header comment for exactly why: the official CLI's --db-url mode
// requires Docker to pull a helper image from Docker Hub, which this
// sandbox's network policy does not allow (confirmed — Docker itself
// runs; the registry pull is what's blocked).
//
// Covers Tables (Row/Insert/Update) and Enums, matching the official
// tool's shape for those two sections exactly, so `createServerClient
// <Database>()` and `supabase.from("x").select()` type inference work
// the same way they would with an officially-generated file. Functions
// and Views are intentionally NOT included — see the generator script's
// header for why partial coverage there would be worse than omission.
//
// This file should be regenerated with the OFFICIAL command once a
// real Docker + internet environment is available:
//   npx supabase gen types typescript --db-url "<connection-string>" \
//     > src/lib/supabase/database.types.ts
// Everything in this file was verified against the actual schema
// produced by every migration in supabase/migrations/, applied to a
// live PostgreSQL 16 instance — not hand-written or guessed.
// =============================================================================

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      advaita_principles: {
        Row: {
          wisdom_entry_id: string;
          source_work: string | null;
          tradition_note: string | null;
        };
        Insert: {
          wisdom_entry_id: string;
          source_work?: string | null;
          tradition_note?: string | null;
        };
        Update: {
          wisdom_entry_id?: string;
          source_work?: string | null;
          tradition_note?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "advaita_principles_wisdom_entry_id_fkey";
            columns: ["wisdom_entry_id"];
            isOneToOne: false;
            referencedRelation: "wisdom_entries";
            referencedColumns: ["id"];
          },
        ];
      };
      ai_jobs: {
        Row: {
          id: string;
          publication_id: string;
          issue_id: string | null;
          block_id: string | null;
          status: Database["public"]["Enums"]["ai_job_status"];
          provider: Database["public"]["Enums"]["ai_provider"];
          model: string;
          params: Json;
          prompt: string | null;
          result: Json | null;
          token_usage: Json | null;
          cost_usd: number | null;
          error: string | null;
          created_by: string;
          created_at: string;
          started_at: string | null;
          completed_at: string | null;
          function_id: Database["public"]["Enums"]["ai_function"] | null;
        };
        Insert: {
          id?: string;
          publication_id: string;
          issue_id?: string | null;
          block_id?: string | null;
          status?: Database["public"]["Enums"]["ai_job_status"];
          provider: Database["public"]["Enums"]["ai_provider"];
          model: string;
          params?: Json;
          prompt?: string | null;
          result?: Json | null;
          token_usage?: Json | null;
          cost_usd?: number | null;
          error?: string | null;
          created_by: string;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          function_id?: Database["public"]["Enums"]["ai_function"] | null;
        };
        Update: {
          id?: string;
          publication_id?: string;
          issue_id?: string | null;
          block_id?: string | null;
          status?: Database["public"]["Enums"]["ai_job_status"];
          provider?: Database["public"]["Enums"]["ai_provider"];
          model?: string;
          params?: Json;
          prompt?: string | null;
          result?: Json | null;
          token_usage?: Json | null;
          cost_usd?: number | null;
          error?: string | null;
          created_by?: string;
          created_at?: string;
          started_at?: string | null;
          completed_at?: string | null;
          function_id?: Database["public"]["Enums"]["ai_function"] | null;
        };
        Relationships: [
          {
            foreignKeyName: "ai_jobs_block_id_fkey";
            columns: ["block_id"];
            isOneToOne: false;
            referencedRelation: "blocks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ai_jobs_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ai_jobs_issue_id_fkey";
            columns: ["issue_id"];
            isOneToOne: false;
            referencedRelation: "issues";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ai_jobs_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "publications";
            referencedColumns: ["id"];
          },
        ];
      };
      analytics_events: {
        Row: {
          id: string;
          event_type: string;
          entity_type: Database["public"]["Enums"]["reference_entity_type"] | null;
          entity_id: string | null;
          user_id: string | null;
          publication_id: string | null;
          metadata: Json;
          occurred_at: string;
        };
        Insert: {
          id?: string;
          event_type: string;
          entity_type?: Database["public"]["Enums"]["reference_entity_type"] | null;
          entity_id?: string | null;
          user_id?: string | null;
          publication_id?: string | null;
          metadata?: Json;
          occurred_at?: string;
        };
        Update: {
          id?: string;
          event_type?: string;
          entity_type?: Database["public"]["Enums"]["reference_entity_type"] | null;
          entity_id?: string | null;
          user_id?: string | null;
          publication_id?: string | null;
          metadata?: Json;
          occurred_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "analytics_events_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "publications";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "analytics_events_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      article_companies: {
        Row: {
          article_id: string;
          company_id: string;
        };
        Insert: {
          article_id: string;
          company_id: string;
        };
        Update: {
          article_id?: string;
          company_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "article_companies_article_id_fkey";
            columns: ["article_id"];
            isOneToOne: false;
            referencedRelation: "articles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "article_companies_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
        ];
      };
      article_technologies: {
        Row: {
          article_id: string;
          technology_id: string;
        };
        Insert: {
          article_id: string;
          technology_id: string;
        };
        Update: {
          article_id?: string;
          technology_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "article_technologies_article_id_fkey";
            columns: ["article_id"];
            isOneToOne: false;
            referencedRelation: "articles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "article_technologies_technology_id_fkey";
            columns: ["technology_id"];
            isOneToOne: false;
            referencedRelation: "technologies";
            referencedColumns: ["id"];
          },
        ];
      };
      articles: {
        Row: {
          id: string;
          publication_id: string;
          title: string;
          slug: string;
          status: Database["public"]["Enums"]["issue_status"];
          published_at: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          search_vector: unknown | null;
          embedding: string | null;
        };
        Insert: {
          id?: string;
          publication_id: string;
          title: string;
          slug: string;
          status?: Database["public"]["Enums"]["issue_status"];
          published_at?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          search_vector?: unknown | null;
          embedding?: string | null;
        };
        Update: {
          id?: string;
          publication_id?: string;
          title?: string;
          slug?: string;
          status?: Database["public"]["Enums"]["issue_status"];
          published_at?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          search_vector?: unknown | null;
          embedding?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "articles_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "articles_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "publications";
            referencedColumns: ["id"];
          },
        ];
      };
      audit_logs: {
        Row: {
          id: string;
          actor_id: string | null;
          action: string;
          entity_type: string;
          entity_id: string | null;
          before: Json | null;
          after: Json | null;
          occurred_at: string;
        };
        Insert: {
          id?: string;
          actor_id?: string | null;
          action: string;
          entity_type: string;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          occurred_at?: string;
        };
        Update: {
          id?: string;
          actor_id?: string | null;
          action?: string;
          entity_type?: string;
          entity_id?: string | null;
          before?: Json | null;
          after?: Json | null;
          occurred_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_logs_actor_id_fkey";
            columns: ["actor_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      blocks: {
        Row: {
          id: string;
          section_id: string;
          type: Database["public"]["Enums"]["block_type"];
          position: number;
          payload: Json;
          ai_generated: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          search_vector: unknown | null;
          embedding: string | null;
          issue_id: string | null;
          last_edited_by: string | null;
          last_edited_at: string;
        };
        Insert: {
          id?: string;
          section_id: string;
          type: Database["public"]["Enums"]["block_type"];
          position?: number;
          payload?: Json;
          ai_generated?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: unknown | null;
          embedding?: string | null;
          issue_id?: string | null;
          last_edited_by?: string | null;
          last_edited_at?: string;
        };
        Update: {
          id?: string;
          section_id?: string;
          type?: Database["public"]["Enums"]["block_type"];
          position?: number;
          payload?: Json;
          ai_generated?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: unknown | null;
          embedding?: string | null;
          issue_id?: string | null;
          last_edited_by?: string | null;
          last_edited_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "blocks_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "blocks_issue_id_fkey";
            columns: ["issue_id"];
            isOneToOne: false;
            referencedRelation: "issues";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "blocks_last_edited_by_fkey";
            columns: ["last_edited_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "blocks_section_id_fkey";
            columns: ["section_id"];
            isOneToOne: false;
            referencedRelation: "sections";
            referencedColumns: ["id"];
          },
        ];
      };
      books: {
        Row: {
          id: string;
          title: string;
          author: string | null;
          isbn: string | null;
          description: string | null;
          url: string | null;
          created_at: string;
          search_vector: unknown | null;
        };
        Insert: {
          id?: string;
          title: string;
          author?: string | null;
          isbn?: string | null;
          description?: string | null;
          url?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Update: {
          id?: string;
          title?: string;
          author?: string | null;
          isbn?: string | null;
          description?: string | null;
          url?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Relationships: [];
      };
      chanakya_niti_verses: {
        Row: {
          wisdom_entry_id: string;
          chapter: number;
          verse: number;
        };
        Insert: {
          wisdom_entry_id: string;
          chapter: number;
          verse: number;
        };
        Update: {
          wisdom_entry_id?: string;
          chapter?: number;
          verse?: number;
        };
        Relationships: [
          {
            foreignKeyName: "chanakya_niti_verses_wisdom_entry_id_fkey";
            columns: ["wisdom_entry_id"];
            isOneToOne: false;
            referencedRelation: "wisdom_entries";
            referencedColumns: ["id"];
          },
        ];
      };
      companies: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          website_url: string | null;
          logo_url: string | null;
          created_at: string;
          updated_at: string;
          search_vector: unknown | null;
          embedding: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          website_url?: string | null;
          logo_url?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: unknown | null;
          embedding?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          website_url?: string | null;
          logo_url?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: unknown | null;
          embedding?: string | null;
        };
        Relationships: [];
      };
      courses: {
        Row: {
          id: string;
          title: string;
          provider: string | null;
          url: string | null;
          description: string | null;
          created_at: string;
          search_vector: unknown | null;
        };
        Insert: {
          id?: string;
          title: string;
          provider?: string | null;
          url?: string | null;
          description?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Update: {
          id?: string;
          title?: string;
          provider?: string | null;
          url?: string | null;
          description?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Relationships: [];
      };
      delivery_logs: {
        Row: {
          id: string;
          issue_id: string;
          subscriber_id: string;
          channel: Database["public"]["Enums"]["delivery_channel"];
          status: Database["public"]["Enums"]["delivery_status"];
          sent_at: string | null;
          opened_at: string | null;
          clicked_at: string | null;
          error: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          issue_id: string;
          subscriber_id: string;
          channel: Database["public"]["Enums"]["delivery_channel"];
          status?: Database["public"]["Enums"]["delivery_status"];
          sent_at?: string | null;
          opened_at?: string | null;
          clicked_at?: string | null;
          error?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          issue_id?: string;
          subscriber_id?: string;
          channel?: Database["public"]["Enums"]["delivery_channel"];
          status?: Database["public"]["Enums"]["delivery_status"];
          sent_at?: string | null;
          opened_at?: string | null;
          clicked_at?: string | null;
          error?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "delivery_logs_issue_id_fkey";
            columns: ["issue_id"];
            isOneToOne: false;
            referencedRelation: "issues";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "delivery_logs_subscriber_id_fkey";
            columns: ["subscriber_id"];
            isOneToOne: false;
            referencedRelation: "subscribers";
            referencedColumns: ["id"];
          },
        ];
      };
      embedding_jobs: {
        Row: {
          id: string;
          entity_type: Database["public"]["Enums"]["reference_entity_type"];
          entity_id: string;
          status: Database["public"]["Enums"]["ai_job_status"];
          error: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          entity_type: Database["public"]["Enums"]["reference_entity_type"];
          entity_id: string;
          status?: Database["public"]["Enums"]["ai_job_status"];
          error?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          entity_type?: Database["public"]["Enums"]["reference_entity_type"];
          entity_id?: string;
          status?: Database["public"]["Enums"]["ai_job_status"];
          error?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [];
      };
      entity_tags: {
        Row: {
          tag_id: string;
          entity_type: Database["public"]["Enums"]["reference_entity_type"];
          entity_id: string;
        };
        Insert: {
          tag_id: string;
          entity_type: Database["public"]["Enums"]["reference_entity_type"];
          entity_id: string;
        };
        Update: {
          tag_id?: string;
          entity_type?: Database["public"]["Enums"]["reference_entity_type"];
          entity_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "entity_tags_tag_id_fkey";
            columns: ["tag_id"];
            isOneToOne: false;
            referencedRelation: "tags";
            referencedColumns: ["id"];
          },
        ];
      };
      gita_verses: {
        Row: {
          wisdom_entry_id: string;
          chapter: number;
          verse: number;
        };
        Insert: {
          wisdom_entry_id: string;
          chapter: number;
          verse: number;
        };
        Update: {
          wisdom_entry_id?: string;
          chapter?: number;
          verse?: number;
        };
        Relationships: [
          {
            foreignKeyName: "gita_verses_wisdom_entry_id_fkey";
            columns: ["wisdom_entry_id"];
            isOneToOne: false;
            referencedRelation: "wisdom_entries";
            referencedColumns: ["id"];
          },
        ];
      };
      github_repositories: {
        Row: {
          id: string;
          owner: string;
          name: string;
          url: string;
          description: string | null;
          stars: number | null;
          last_synced_at: string | null;
          created_at: string;
          search_vector: unknown | null;
        };
        Insert: {
          id?: string;
          owner: string;
          name: string;
          url: string;
          description?: string | null;
          stars?: number | null;
          last_synced_at?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Update: {
          id?: string;
          owner?: string;
          name?: string;
          url?: string;
          description?: string | null;
          stars?: number | null;
          last_synced_at?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Relationships: [];
      };
      hitopadesha_stories: {
        Row: {
          wisdom_entry_id: string;
          section_name: string;
          story_title: string;
        };
        Insert: {
          wisdom_entry_id: string;
          section_name: string;
          story_title: string;
        };
        Update: {
          wisdom_entry_id?: string;
          section_name?: string;
          story_title?: string;
        };
        Relationships: [
          {
            foreignKeyName: "hitopadesha_stories_wisdom_entry_id_fkey";
            columns: ["wisdom_entry_id"];
            isOneToOne: false;
            referencedRelation: "wisdom_entries";
            referencedColumns: ["id"];
          },
        ];
      };
      invitations: {
        Row: {
          id: string;
          email: string;
          organization_id: string | null;
          publication_id: string | null;
          role: string;
          token: string;
          status: Database["public"]["Enums"]["invitation_status"];
          invited_by: string;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          organization_id?: string | null;
          publication_id?: string | null;
          role: string;
          token: string;
          status?: Database["public"]["Enums"]["invitation_status"];
          invited_by: string;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          organization_id?: string | null;
          publication_id?: string | null;
          role?: string;
          token?: string;
          status?: Database["public"]["Enums"]["invitation_status"];
          invited_by?: string;
          expires_at?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "invitations_invited_by_fkey";
            columns: ["invited_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invitations_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "invitations_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "publications";
            referencedColumns: ["id"];
          },
        ];
      };
      issue_revisions: {
        Row: {
          id: string;
          issue_id: string;
          snapshot: Json;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          issue_id: string;
          snapshot: Json;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          issue_id?: string;
          snapshot?: Json;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "issue_revisions_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "issue_revisions_issue_id_fkey";
            columns: ["issue_id"];
            isOneToOne: false;
            referencedRelation: "issues";
            referencedColumns: ["id"];
          },
        ];
      };
      issues: {
        Row: {
          id: string;
          publication_id: string;
          title: string;
          slug: string;
          status: Database["public"]["Enums"]["issue_status"];
          scheduled_at: string | null;
          published_at: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          search_vector: unknown | null;
          embedding: string | null;
        };
        Insert: {
          id?: string;
          publication_id: string;
          title: string;
          slug: string;
          status?: Database["public"]["Enums"]["issue_status"];
          scheduled_at?: string | null;
          published_at?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          search_vector?: unknown | null;
          embedding?: string | null;
        };
        Update: {
          id?: string;
          publication_id?: string;
          title?: string;
          slug?: string;
          status?: Database["public"]["Enums"]["issue_status"];
          scheduled_at?: string | null;
          published_at?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          search_vector?: unknown | null;
          embedding?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "issues_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "issues_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "publications";
            referencedColumns: ["id"];
          },
        ];
      };
      knowledge_graph_edges: {
        Row: {
          id: string;
          source_type: Database["public"]["Enums"]["reference_entity_type"];
          source_id: string;
          target_type: Database["public"]["Enums"]["reference_entity_type"];
          target_id: string;
          relation_type: string;
          created_by: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          source_type: Database["public"]["Enums"]["reference_entity_type"];
          source_id: string;
          target_type: Database["public"]["Enums"]["reference_entity_type"];
          target_id: string;
          relation_type?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          source_type?: Database["public"]["Enums"]["reference_entity_type"];
          source_id?: string;
          target_type?: Database["public"]["Enums"]["reference_entity_type"];
          target_id?: string;
          relation_type?: string;
          created_by?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "knowledge_graph_edges_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      notifications: {
        Row: {
          id: string;
          user_id: string;
          type: string;
          payload: Json;
          read_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          type: string;
          payload?: Json;
          read_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          type?: string;
          payload?: Json;
          read_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      organization_members: {
        Row: {
          organization_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["organization_role"];
          created_at: string;
        };
        Insert: {
          organization_id: string;
          user_id: string;
          role?: Database["public"]["Enums"]["organization_role"];
          created_at?: string;
        };
        Update: {
          organization_id?: string;
          user_id?: string;
          role?: Database["public"]["Enums"]["organization_role"];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "organization_members_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "organization_members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      organizations: {
        Row: {
          id: string;
          name: string;
          type: Database["public"]["Enums"]["organization_type"];
          created_by: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          type: Database["public"]["Enums"]["organization_type"];
          created_by: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          type?: Database["public"]["Enums"]["organization_type"];
          created_by?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "organizations_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      panchatantra_tales: {
        Row: {
          wisdom_entry_id: string;
          tantra_number: number;
          tantra_name: string;
          tale_title: string;
        };
        Insert: {
          wisdom_entry_id: string;
          tantra_number: number;
          tantra_name: string;
          tale_title: string;
        };
        Update: {
          wisdom_entry_id?: string;
          tantra_number?: number;
          tantra_name?: string;
          tale_title?: string;
        };
        Relationships: [
          {
            foreignKeyName: "panchatantra_tales_wisdom_entry_id_fkey";
            columns: ["wisdom_entry_id"];
            isOneToOne: false;
            referencedRelation: "wisdom_entries";
            referencedColumns: ["id"];
          },
        ];
      };
      papers: {
        Row: {
          id: string;
          title: string;
          authors: string[];
          url: string | null;
          abstract: string | null;
          published_at: string | null;
          created_at: string;
          search_vector: unknown | null;
        };
        Insert: {
          id?: string;
          title: string;
          authors?: string[];
          url?: string | null;
          abstract?: string | null;
          published_at?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Update: {
          id?: string;
          title?: string;
          authors?: string[];
          url?: string | null;
          abstract?: string | null;
          published_at?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Relationships: [];
      };
      people: {
        Row: {
          id: string;
          full_name: string;
          slug: string;
          bio: string | null;
          avatar_url: string | null;
          external_links: Json;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          search_vector: unknown | null;
        };
        Insert: {
          id?: string;
          full_name: string;
          slug: string;
          bio?: string | null;
          avatar_url?: string | null;
          external_links?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: unknown | null;
        };
        Update: {
          id?: string;
          full_name?: string;
          slug?: string;
          bio?: string | null;
          avatar_url?: string | null;
          external_links?: Json;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: unknown | null;
        };
        Relationships: [
          {
            foreignKeyName: "people_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      podcasts: {
        Row: {
          id: string;
          title: string;
          platform: string | null;
          url: string;
          description: string | null;
          created_at: string;
          search_vector: unknown | null;
        };
        Insert: {
          id?: string;
          title: string;
          platform?: string | null;
          url: string;
          description?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Update: {
          id?: string;
          title?: string;
          platform?: string | null;
          url?: string;
          description?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          id: string;
          full_name: string | null;
          avatar_url: string | null;
          role: Database["public"]["Enums"]["platform_role"];
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: Database["public"]["Enums"]["platform_role"];
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          role?: Database["public"]["Enums"]["platform_role"];
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      prompt_templates: {
        Row: {
          id: string;
          block_type: Database["public"]["Enums"]["block_type"];
          name: string;
          template_text: string;
          variables: Json;
          is_active: boolean;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          publication_id: string | null;
        };
        Insert: {
          id?: string;
          block_type: Database["public"]["Enums"]["block_type"];
          name: string;
          template_text: string;
          variables?: Json;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          publication_id?: string | null;
        };
        Update: {
          id?: string;
          block_type?: Database["public"]["Enums"]["block_type"];
          name?: string;
          template_text?: string;
          variables?: Json;
          is_active?: boolean;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          publication_id?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "prompt_templates_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "prompt_templates_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "publications";
            referencedColumns: ["id"];
          },
        ];
      };
      publication_members: {
        Row: {
          publication_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["membership_role"];
          created_at: string;
        };
        Insert: {
          publication_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["membership_role"];
          created_at?: string;
        };
        Update: {
          publication_id?: string;
          user_id?: string;
          role?: Database["public"]["Enums"]["membership_role"];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "publication_members_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "publications";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "publication_members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      publication_templates: {
        Row: {
          id: string;
          publication_id: string;
          channel: Database["public"]["Enums"]["template_channel"];
          config: Json;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          publication_id: string;
          channel: Database["public"]["Enums"]["template_channel"];
          config?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          publication_id?: string;
          channel?: Database["public"]["Enums"]["template_channel"];
          config?: Json;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "publication_templates_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "publications";
            referencedColumns: ["id"];
          },
        ];
      };
      publications: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          theme: Json;
          branding: Json;
          editorial_guidelines: string | null;
          cadence: string | null;
          status: Database["public"]["Enums"]["publication_status"];
          created_by: string;
          created_at: string;
          updated_at: string;
          archived_at: string | null;
          logo_url: string | null;
          publishing_schedule: Json;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          theme?: Json;
          branding?: Json;
          editorial_guidelines?: string | null;
          cadence?: string | null;
          status?: Database["public"]["Enums"]["publication_status"];
          created_by: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          logo_url?: string | null;
          publishing_schedule?: Json;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          theme?: Json;
          branding?: Json;
          editorial_guidelines?: string | null;
          cadence?: string | null;
          status?: Database["public"]["Enums"]["publication_status"];
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          archived_at?: string | null;
          logo_url?: string | null;
          publishing_schedule?: Json;
        };
        Relationships: [
          {
            foreignKeyName: "publications_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      scheduled_jobs: {
        Row: {
          id: string;
          issue_id: string;
          run_at: string;
          status: Database["public"]["Enums"]["scheduled_job_status"];
          error: string | null;
          created_at: string;
          completed_at: string | null;
        };
        Insert: {
          id?: string;
          issue_id: string;
          run_at: string;
          status?: Database["public"]["Enums"]["scheduled_job_status"];
          error?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Update: {
          id?: string;
          issue_id?: string;
          run_at?: string;
          status?: Database["public"]["Enums"]["scheduled_job_status"];
          error?: string | null;
          created_at?: string;
          completed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "scheduled_jobs_issue_id_fkey";
            columns: ["issue_id"];
            isOneToOne: false;
            referencedRelation: "issues";
            referencedColumns: ["id"];
          },
        ];
      };
      sections: {
        Row: {
          id: string;
          issue_id: string | null;
          article_id: string | null;
          title: string | null;
          position: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          issue_id?: string | null;
          article_id?: string | null;
          title?: string | null;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          issue_id?: string | null;
          article_id?: string | null;
          title?: string | null;
          position?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "sections_article_id_fkey";
            columns: ["article_id"];
            isOneToOne: false;
            referencedRelation: "articles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "sections_issue_id_fkey";
            columns: ["issue_id"];
            isOneToOne: false;
            referencedRelation: "issues";
            referencedColumns: ["id"];
          },
        ];
      };
      settings: {
        Row: {
          id: string;
          publication_id: string | null;
          key: string;
          value: Json;
          updated_at: string;
        };
        Insert: {
          id?: string;
          publication_id?: string | null;
          key: string;
          value: Json;
          updated_at?: string;
        };
        Update: {
          id?: string;
          publication_id?: string | null;
          key?: string;
          value?: Json;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "settings_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "publications";
            referencedColumns: ["id"];
          },
        ];
      };
      sources: {
        Row: {
          id: string;
          title: string;
          url: string | null;
          publisher: string | null;
          source_type: string | null;
          retrieved_at: string | null;
          created_at: string;
          search_vector: unknown | null;
        };
        Insert: {
          id?: string;
          title: string;
          url?: string | null;
          publisher?: string | null;
          source_type?: string | null;
          retrieved_at?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Update: {
          id?: string;
          title?: string;
          url?: string | null;
          publisher?: string | null;
          source_type?: string | null;
          retrieved_at?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Relationships: [];
      };
      subhashitams: {
        Row: {
          wisdom_entry_id: string;
          meter: string | null;
          attributed_to: string | null;
        };
        Insert: {
          wisdom_entry_id: string;
          meter?: string | null;
          attributed_to?: string | null;
        };
        Update: {
          wisdom_entry_id?: string;
          meter?: string | null;
          attributed_to?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "subhashitams_wisdom_entry_id_fkey";
            columns: ["wisdom_entry_id"];
            isOneToOne: false;
            referencedRelation: "wisdom_entries";
            referencedColumns: ["id"];
          },
        ];
      };
      subscribers: {
        Row: {
          id: string;
          email: string;
          profile_id: string | null;
          organization_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          email: string;
          profile_id?: string | null;
          organization_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          profile_id?: string | null;
          organization_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subscribers_organization_id_fkey";
            columns: ["organization_id"];
            isOneToOne: false;
            referencedRelation: "organizations";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscribers_profile_id_fkey";
            columns: ["profile_id"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      subscriptions: {
        Row: {
          id: string;
          subscriber_id: string;
          publication_id: string;
          status: Database["public"]["Enums"]["subscription_status"];
          subscribed_at: string;
          unsubscribed_at: string | null;
        };
        Insert: {
          id?: string;
          subscriber_id: string;
          publication_id: string;
          status?: Database["public"]["Enums"]["subscription_status"];
          subscribed_at?: string;
          unsubscribed_at?: string | null;
        };
        Update: {
          id?: string;
          subscriber_id?: string;
          publication_id?: string;
          status?: Database["public"]["Enums"]["subscription_status"];
          subscribed_at?: string;
          unsubscribed_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "subscriptions_publication_id_fkey";
            columns: ["publication_id"];
            isOneToOne: false;
            referencedRelation: "publications";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "subscriptions_subscriber_id_fkey";
            columns: ["subscriber_id"];
            isOneToOne: false;
            referencedRelation: "subscribers";
            referencedColumns: ["id"];
          },
        ];
      };
      tags: {
        Row: {
          id: string;
          name: string;
          slug: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
        };
        Relationships: [];
      };
      technologies: {
        Row: {
          id: string;
          name: string;
          slug: string;
          category: string | null;
          description: string | null;
          website_url: string | null;
          created_at: string;
          updated_at: string;
          search_vector: unknown | null;
          embedding: string | null;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          category?: string | null;
          description?: string | null;
          website_url?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: unknown | null;
          embedding?: string | null;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          category?: string | null;
          description?: string | null;
          website_url?: string | null;
          created_at?: string;
          updated_at?: string;
          search_vector?: unknown | null;
          embedding?: string | null;
        };
        Relationships: [];
      };
      technology_companies: {
        Row: {
          technology_id: string;
          company_id: string;
          relationship: string | null;
        };
        Insert: {
          technology_id: string;
          company_id: string;
          relationship?: string | null;
        };
        Update: {
          technology_id?: string;
          company_id?: string;
          relationship?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "technology_companies_company_id_fkey";
            columns: ["company_id"];
            isOneToOne: false;
            referencedRelation: "companies";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "technology_companies_technology_id_fkey";
            columns: ["technology_id"];
            isOneToOne: false;
            referencedRelation: "technologies";
            referencedColumns: ["id"];
          },
        ];
      };
      upanishad_verses: {
        Row: {
          wisdom_entry_id: string;
          upanishad_name: string;
          chapter: number | null;
          verse: number | null;
        };
        Insert: {
          wisdom_entry_id: string;
          upanishad_name: string;
          chapter?: number | null;
          verse?: number | null;
        };
        Update: {
          wisdom_entry_id?: string;
          upanishad_name?: string;
          chapter?: number | null;
          verse?: number | null;
        };
        Relationships: [
          {
            foreignKeyName: "upanishad_verses_wisdom_entry_id_fkey";
            columns: ["wisdom_entry_id"];
            isOneToOne: false;
            referencedRelation: "wisdom_entries";
            referencedColumns: ["id"];
          },
        ];
      };
      videos: {
        Row: {
          id: string;
          title: string;
          platform: string | null;
          url: string;
          description: string | null;
          created_at: string;
          search_vector: unknown | null;
        };
        Insert: {
          id?: string;
          title: string;
          platform?: string | null;
          url: string;
          description?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Update: {
          id?: string;
          title?: string;
          platform?: string | null;
          url?: string;
          description?: string | null;
          created_at?: string;
          search_vector?: unknown | null;
        };
        Relationships: [];
      };
      wisdom_categories: {
        Row: {
          id: string;
          name: string;
          slug: string;
          description: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          description?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          description?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      wisdom_entries: {
        Row: {
          id: string;
          category_id: string | null;
          title: string;
          source_type: Database["public"]["Enums"]["wisdom_source_type"];
          source_text: string | null;
          iast: string | null;
          translation: string;
          context: string | null;
          commentary: string | null;
          tech_lens: string | null;
          career_lens: string | null;
          leadership_lens: string | null;
          decision_lens: string | null;
          keywords: string[];
          references_json: Json;
          review_status: Database["public"]["Enums"]["wisdom_review_status"];
          reviewed_by: string | null;
          reviewed_at: string | null;
          created_by: string;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          search_vector: unknown | null;
          embedding: string | null;
          review_notes: string | null;
        };
        Insert: {
          id?: string;
          category_id?: string | null;
          title: string;
          source_type: Database["public"]["Enums"]["wisdom_source_type"];
          source_text?: string | null;
          iast?: string | null;
          translation: string;
          context?: string | null;
          commentary?: string | null;
          tech_lens?: string | null;
          career_lens?: string | null;
          leadership_lens?: string | null;
          decision_lens?: string | null;
          keywords?: string[];
          references_json?: Json;
          review_status?: Database["public"]["Enums"]["wisdom_review_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_by: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          search_vector?: unknown | null;
          embedding?: string | null;
          review_notes?: string | null;
        };
        Update: {
          id?: string;
          category_id?: string | null;
          title?: string;
          source_type?: Database["public"]["Enums"]["wisdom_source_type"];
          source_text?: string | null;
          iast?: string | null;
          translation?: string;
          context?: string | null;
          commentary?: string | null;
          tech_lens?: string | null;
          career_lens?: string | null;
          leadership_lens?: string | null;
          decision_lens?: string | null;
          keywords?: string[];
          references_json?: Json;
          review_status?: Database["public"]["Enums"]["wisdom_review_status"];
          reviewed_by?: string | null;
          reviewed_at?: string | null;
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          search_vector?: unknown | null;
          embedding?: string | null;
          review_notes?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "wisdom_entries_category_id_fkey";
            columns: ["category_id"];
            isOneToOne: false;
            referencedRelation: "wisdom_categories";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "wisdom_entries_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "wisdom_entries_reviewed_by_fkey";
            columns: ["reviewed_by"];
            isOneToOne: false;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          },
        ];
      };
      wisdom_exercises: {
        Row: {
          id: string;
          wisdom_entry_id: string;
          exercise: string;
          position: number;
        };
        Insert: {
          id?: string;
          wisdom_entry_id: string;
          exercise: string;
          position?: number;
        };
        Update: {
          id?: string;
          wisdom_entry_id?: string;
          exercise?: string;
          position?: number;
        };
        Relationships: [
          {
            foreignKeyName: "wisdom_exercises_wisdom_entry_id_fkey";
            columns: ["wisdom_entry_id"];
            isOneToOne: false;
            referencedRelation: "wisdom_entries";
            referencedColumns: ["id"];
          },
        ];
      };
      wisdom_recommendations: {
        Row: {
          id: string;
          issue_id: string;
          wisdom_entry_id: string;
          score: number;
          rationale: string | null;
          ai_job_id: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          issue_id: string;
          wisdom_entry_id: string;
          score: number;
          rationale?: string | null;
          ai_job_id?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          issue_id?: string;
          wisdom_entry_id?: string;
          score?: number;
          rationale?: string | null;
          ai_job_id?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "wisdom_recommendations_ai_job_id_fkey";
            columns: ["ai_job_id"];
            isOneToOne: false;
            referencedRelation: "ai_jobs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "wisdom_recommendations_issue_id_fkey";
            columns: ["issue_id"];
            isOneToOne: false;
            referencedRelation: "issues";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "wisdom_recommendations_wisdom_entry_id_fkey";
            columns: ["wisdom_entry_id"];
            isOneToOne: false;
            referencedRelation: "wisdom_entries";
            referencedColumns: ["id"];
          },
        ];
      };
      wisdom_reflection_questions: {
        Row: {
          id: string;
          wisdom_entry_id: string;
          question: string;
          position: number;
        };
        Insert: {
          id?: string;
          wisdom_entry_id: string;
          question: string;
          position?: number;
        };
        Update: {
          id?: string;
          wisdom_entry_id?: string;
          question?: string;
          position?: number;
        };
        Relationships: [
          {
            foreignKeyName: "wisdom_reflection_questions_wisdom_entry_id_fkey";
            columns: ["wisdom_entry_id"];
            isOneToOne: false;
            referencedRelation: "wisdom_entries";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      ai_function:
        | "generate_issue"
        | "rewrite"
        | "summarize"
        | "improve_writing"
        | "suggest_headlines"
        | "suggest_images"
        | "generate_linkedin_post"
        | "generate_email"
        | "generate_pdf_content"
        | "generate_seo_metadata"
        | "recommend_wisdom"
        | "suggest_graph_connections"
        | "recommend_related_entities";
      ai_job_status: "pending" | "running" | "completed" | "failed";
      ai_provider: "openai" | "anthropic";
      block_type:
        | "heading"
        | "paragraph"
        | "image"
        | "quote"
        | "table_block"
        | "chart"
        | "hero_story"
        | "signal_card"
        | "career_insight"
        | "research_summary"
        | "timeline"
        | "github_repository_block"
        | "book_recommendation"
        | "company_profile"
        | "technology_radar"
        | "todays_wisdom"
        | "reflection"
        | "action_checklist"
        | "decision_framework";
      delivery_channel: "email" | "web" | "pdf";
      delivery_status: "queued" | "sent" | "delivered" | "opened" | "clicked" | "failed";
      invitation_status: "pending" | "accepted" | "expired" | "revoked";
      issue_status: "draft" | "in_review" | "scheduled" | "published" | "archived";
      membership_role: "editor_in_chief" | "editor" | "writer" | "researcher";
      organization_role: "admin" | "member";
      organization_type: "enterprise" | "university" | "company";
      platform_role:
        | "super_admin"
        | "editor_in_chief"
        | "editor"
        | "writer"
        | "researcher"
        | "subscriber"
        | "premium_subscriber";
      publication_status: "active" | "archived";
      reference_entity_type:
        | "article"
        | "issue"
        | "technology"
        | "company"
        | "book"
        | "paper"
        | "course"
        | "video"
        | "podcast"
        | "github_repository"
        | "wisdom_entry"
        | "source"
        | "person";
      scheduled_job_status: "pending" | "running" | "completed" | "failed";
      subscription_status: "active" | "unsubscribed" | "bounced";
      template_channel: "email" | "pdf" | "web";
      wisdom_review_status: "draft" | "in_review" | "approved" | "rejected";
      wisdom_source_type:
        | "subhashitam"
        | "gita_verse"
        | "advaita_principle"
        | "other"
        | "upanishad_verse"
        | "chanakya_niti_verse"
        | "panchatantra_tale"
        | "hitopadesha_story";
    };
    CompositeTypes: Record<string, never>;
  };
}
